services:
  app:
    build:
      context: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "9501:9501"
    environment:
      APP_ENV: dev
      SCAN_CACHEABLE: "false"

      # DB (Hypert lê do .env, mas deixo aqui como fallback)
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: conta_digital
      DB_USERNAME: conta_digital
      DB_PASSWORD: conta_digital

      # Mailhog (SMTP)
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: ""
      MAIL_FROM_ADDRESS: "no-reply@contadigital.local"
      MAIL_FROM_NAME: "Conta Digital"

    depends_on:
      mysql:
        condition: service_healthy
      mailhog:
        condition: service_started

    command: ["php", "bin/hyperf.php", "start"]

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conta_digital
      MYSQL_USER: conta_digital
      MYSQL_PASSWORD: conta_digital
      TZ: America/Sao_Paulo
    ports:
      - "3307:3306" # porta externa 3307 para não conflitar com MySQL local
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025" # UI do Mailhog
      - "1025:1025" # SMTP
    environment:
      MH_STORAGE: maildir

volumes:
  mysql_data:
